# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       libksba
Summary:    X.509 library
Version:    1.0.1
Release:    1
Group:      System/Libraries
License:    GPLv2+
URL:        http://www.gnupg.org/
Source0:    ftp://ftp.gnupg.org/gcrypt/libksba/libksba-%{version}.tar.bz2
Source100:  libksba.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(libgcrypt)
BuildRequires:  gawk
BuildRequires:  libgpg-error-devel >= 1.2


%description
KSBA is a library designed to build software based on the X.509 and
CMS protocols.



%package devel
Summary:    Development headers and libraries for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
A library designed to build software based on the X.509 and
CMS protocols.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install 

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS ChangeLog COPYING NEWS README* THANKS TODO VERSION
%{_libdir}/lib*.so.*
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_bindir}/ksba-config
%{_libdir}/lib*.so
%{_includedir}/*
%{_datadir}/aclocal/*
%{_infodir}/*
# << files devel

